const {
  NEXT_PUBLIC_CONTENTFUL_AUTH_TOKEN,
  NEXT_PUBLIC_CONTENTFUL_CONTENT_ID,
  NEXT_PUBLIC_CONTENTFUL_ENVIRONMENT,
  NEXT_PUBLIC_CONTENTFUL_SPACE_ID,
  NEXT_PUBLIC_STRAPI_API_URL,
  NEXT_PUBLIC_STRAPI_AUTH_TOKEN,
} = process.env;

export {
  NEXT_PUBLIC_CONTENTFUL_AUTH_TOKEN,
  NEXT_PUBLIC_CONTENTFUL_CONTENT_ID,
  NEXT_PUBLIC_CONTENTFUL_ENVIRONMENT,
  NEXT_PUBLIC_CONTENTFUL_SPACE_ID,
  NEXT_PUBLIC_STRAPI_API_URL,
  NEXT_PUBLIC_STRAPI_AUTH_TOKEN,
};
