const { NEXT_PUBLIC_STRAPI_API_URL, NEXT_PUBLIC_STRAPI_AUTH_TOKEN, NEXT_PUBLIC_CMS_PROVIDER } =
  process.env;

export { NEXT_PUBLIC_STRAPI_API_URL, NEXT_PUBLIC_STRAPI_AUTH_TOKEN, NEXT_PUBLIC_CMS_PROVIDER };
